spring:
  application:
    name: strava-service
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:user_details
    username: abhay
    password: gupta
    driverClassName: org.h2.Driver
  security:
    oauth2:
      client:
        registration:
          strava:
            client-id: "128948"
            client-secret: "0b2c7e227dac5ca1dd7139c95caebf98f7cec84f"
            scope: read
            redirect-uri: "{baseUrl}/login/oauth2/code/my-running"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
        provider:
          strava:
            authorization-uri: https://www.strava.com/oauth/authorize
            token-uri: https://www.strava.com/oauth/token
            user-info-uri: https://www.strava.com/api/v3/athlete
            user-name-attribute: id

server:
  port: 8090

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


