spring:
  application:
    name: strava-service
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:user_details
    username: abhay
    password: gupta
    driver-class-name: org.h2.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/user-registration/protocol/openid-connect/certs
      client:
        registration:
          strava:
            client-id: ####
            client-secret: ####
            scope: read
            redirect-uri: "{baseUrl}/login/oauth2/code/my-running"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
        provider:
          strava:
            authorization-uri: https://www.strava.com/oauth/authorize
            token-uri: https://www.strava.com/oauth/token
            user-info-uri: https://www.strava.com/api/v3/athlete
            user-name-attribute: id

server:
  port: 8090

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka


